services:
  db:
    container_name: itbms-dev-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
      LANG: C.UTF-8
    volumes:
      - itbms-mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./insert.sql:/app/insert.sql
    ports:
      - "3306:3306"

volumes:
  itbms-mysql-data: