services:
  fe:
    container_name: itbms-fe-container
    build:
      context: ./itbms-frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      - itbms-network
    depends_on:
      - be

  be:
    container_name: itbms-be-container
    build:
      context: ./itbms-backend
      dockerfile: dockerfile
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - itbms-network
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: itbms-db-container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
      LANG: C.UTF-8
    networks:
      - itbms-network
    volumes:
      - itbms-mysql-data:/var/lib/mysql
      - ./itbms-database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./itbms-database/insert.sql:/app/insert.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  itbms-network:

volumes:
  itbms-mysql-data: