services:
  ollama:
    container_name: itbms-ollama-container
    image: ollama/ollama:latest
    volumes:
      - itbms_ollama_data:/root/.ollama
    networks:
      - itbms_network
    # Use 'deploy' for GPU support if available
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    
    # Use entrypoint to run the server and pull a model
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "ollama serve & ollama pull llama3 && wait"
    restart: unless-stopped

  database:
    container_name: itbms-db-container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - itbms_network
    volumes:
      - itbms_mysql_data:/var/lib/mysql
      - ./itbms-database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./itbms-database/insert.sql:/app/insert.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  minio:
    container_name: itbms-minio-container
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # Production security settings
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL:-http://localhost:9001}
    networks:
      - itbms_network
    volumes:
      - itbms_minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    # Only expose ports if you need external access
    # For production, consider using a reverse proxy instead
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
  
  backend:
    container_name: itbms-be-container
    build:
      context: ./itbms-backend
      dockerfile: dockerfile
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    networks:
      - itbms_network
    depends_on:
      database:
        condition: service_healthy
      ollama:
        condition: service_started
      minio:
        condition: service_healthy

  frontend:
    container_name: itbms-fe-container
    build:
      context: ./itbms-frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      - itbms_network
    depends_on:
      - backend

networks:
  itbms_network:

volumes:
  itbms_mysql_data:
  itbms_ollama_data: 
  itbms_minio_data: