spring:
  application:
    name: itbms-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: itbmshop359@gmail.com
    password: hxjhjwvjpczmasfd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /itb-mshop
  error:
    include-stacktrace: on_param

# File Config
file:
  upload-dir: upload_images
  max-size: 2MB
  allowed-types: image/jpeg,image/png,image/webp

# JWT Config
jwt:
  secret: mySecretKey123456789012345678901234567890hfeoiafhaoifhadhiwadhjwoifdhwafiajfaidjsadiosadjifwhwif
  access-token-expiration_ms: 86400000 # 24 hours in milliseconds
  refresh-token-expiration_ms: 86400000

email:
  verification_token_expiration_hr: 24

# Logging
logging:
  level:
    org.springframework.security: DEBUG
    com.example.auth: DEBUG

team:
  code: ms3