spring:
  application:
    name: itbms-backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ms3_itbms_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:rootpass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: none
#    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER:itbmshop359@gmail.com}
    password: ${MAIL_PASSWORD:hxjhjwvjpczmasfd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  ai:
    chat:
      client:
        enabled: false
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      chat:
        options:
          model: gpt-4o-mini
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: llama3

# File Config
file:
  upload-dir: upload_images
  max-size: 2MB
  allowed-types: image/jpeg,image/png,image/webp

# JWT Config
jwt:
  secret: mySecretKey123456789012345678901234567890hfeoiafhaoifhadhiwadhjwoifdhwafiajfaidjsadiosadjifwhwif
  access-token-expiration_ms: 1800000   # 30 minutes
  refresh-token-expiration_ms: 86400000 # 24 hours

# Email
email:
  verification_token_expiration_hr: 24

# Logging
logging:
  level:
    org.springframework.security: DEBUG
    com.example.auth: DEBUG

server:
  port: 8080
  servlet:
    context-path: /itb-mshop
  error:
    include-stacktrace: on_param

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

team:
  code: ms3